import {Alert} from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import * as ImagePicker from 'expo-image-picker';
import * as FileSystem from 'expo-file-system/legacy';
import {sanitiseFilename,createLocalId} from '../utils/downloadUtils';
import {classifyMedia,formatBytes} from '../utils/mediaUtils';
import {addLibraryItems} from './libraryService';
import {recordDiagnostic} from './diagnosticsService';

export const IMPORT_DIR=`${FileSystem.documentDirectory}imports/`;
const LARGE_IMPORT_BYTES=250*1024*1024;
const STORAGE_RESERVE_BYTES=64*1024*1024;
async function ensureImportDirectory(){const info=await FileSystem.getInfoAsync(IMPORT_DIR);if(!info.exists)await FileSystem.makeDirectoryAsync(IMPORT_DIR,{intermediates:true});}
async function uniqueImportUri(name){await ensureImportDirectory();const safe=sanitiseFilename(name||`media_${Date.now()}`,`media_${Date.now()}`);const dot=safe.lastIndexOf('.');const base=dot>0?safe.slice(0,dot):safe;const ext=dot>0?safe.slice(dot):'';for(let i=0;i<10000;i+=1){const candidate=i?`${base} (${i})${ext}`:safe;const uri=`${IMPORT_DIR}${candidate}`;if(!(await FileSystem.getInfoAsync(uri)).exists)return{uri,name:candidate};}throw new Error('Could not allocate a safe import filename.');}
async function confirmLargeCopy(assets){const bytes=(assets||[]).reduce((n,a)=>n+Math.max(0,Number(a.size||a.fileSize)||0),0);if(bytes<LARGE_IMPORT_BYTES)return true;return new Promise(resolve=>Alert.alert('Large managed import',`VideoRip will copy approximately ${formatBytes(bytes)} into managed app storage so these items remain available. Continue?`,[{text:'Cancel',style:'cancel',onPress:()=>resolve(false)},{text:'Import',onPress:()=>resolve(true)}],{cancelable:true,onDismiss:()=>resolve(false)}));}
async function ensureCapacity(bytes){if(!Number.isFinite(bytes)||bytes<=0)return;const free=await FileSystem.getFreeDiskStorageAsync().catch(()=>null);if(Number.isFinite(free)&&bytes+STORAGE_RESERVE_BYTES>free)throw Object.assign(new Error(`Not enough free storage for a ${formatBytes(bytes)} managed copy.`),{code:'INSUFFICIENT_STORAGE'});}
async function ingestAsset(asset,origin){if(!asset?.uri)throw new Error('The selected item does not expose a readable URI.');const sourceName=asset.name||asset.fileName||asset.uri.split('/').pop()||`media_${Date.now()}`;const requestedBytes=Math.max(0,Number(asset.size||asset.fileSize)||0);await ensureCapacity(requestedBytes);const target=await uniqueImportUri(sourceName);await FileSystem.copyAsync({from:asset.uri,to:target.uri});const info=await FileSystem.getInfoAsync(target.uri);if(!info.exists||info.isDirectory)throw new Error(`Could not import ${sourceName}.`);const classified=classifyMedia({name:target.name,mimeType:asset.mimeType,uri:target.uri});return{id:createLocalId(),origin,managed:true,uri:target.uri,name:target.name,originalName:sourceName,mimeType:asset.mimeType||null,size:info.size||requestedBytes,duration:asset.duration?Number(asset.duration)/(asset.duration>100000?1000:1):null,width:asset.width||null,height:asset.height||null,mediaType:classified.mediaType,sourceType:classified.sourceType,container:classified.container,playability:classified.playable===true?'expected':classified.playable===false?'unsupported':'unknown',playabilityReason:classified.reason,importedAt:Date.now(),createdAt:Date.now()};}
async function ingestMany(assets,origin){if(!(await confirmLargeCopy(assets)))return{imported:[],errors:['Import cancelled before copying large selected media.']};const imported=[];const errors=[];for(const asset of assets||[]){try{imported.push(await ingestAsset(asset,origin));}catch(error){errors.push(`${asset?.name||asset?.fileName||'Selected item'}: ${error.message}`);await recordDiagnostic('error',error.code||'IMPORT_ERROR',error.message);}}if(imported.length)await addLibraryItems(imported);return{imported,errors};}
export async function pickDocuments(){const result=await DocumentPicker.getDocumentAsync({type:['video/*','audio/*','application/vnd.apple.mpegurl','application/x-mpegurl','application/dash+xml','application/octet-stream'],multiple:true,copyToCacheDirectory:false});if(result.canceled)return{imported:[],errors:[]};return ingestMany(result.assets,'document');}
export async function pickMedia(){const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['videos'],allowsMultipleSelection:true,selectionLimit:0,quality:1});if(result.canceled)return{imported:[],errors:[]};return ingestMany(result.assets,'mediaPicker');}
export async function ingestSharedPayloads(payloads){const assets=(payloads||[]).flatMap(payload=>{if(!payload?.contentUri||!['audio','video','file'].includes(payload.contentType))return[];return[{uri:payload.contentUri,name:payload.originalName||payload.contentUri.split('/').pop(),mimeType:payload.contentMimeType||payload.mimeType||null,size:payload.contentSize||null}];});return ingestMany(assets,'shared');}
