import React,{useCallback,useState} from 'react';
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import Screen from '../components/Screen';
import {analysePublicPage,analyseUrl} from '../services/linkAnalysisService';
import {useDownload} from '../context/DownloadContext';
import {formatBytes} from '../utils/mediaUtils';

export default function LinksScreen({navigation}){
 const [url,setUrl]=useState('');const [result,setResult]=useState(null);const [error,setError]=useState(null);const [busy,setBusy]=useState(false);const {addDownload}=useDownload();
 const run=useCallback(async()=>{setBusy(true);setError(null);try{const direct=await analyseUrl(url);if(direct.sourceType==='webpage')setResult(await analysePublicPage(url));else setResult(direct);}catch(e){try{setResult(await analysePublicPage(url));}catch(e2){setError(e2.message||e.message);setResult(null);}}finally{setBusy(false);}},[url]);
 const add=useCallback(async(candidate)=>{setBusy(true);setError(null);try{const analysis=await analyseUrl(candidate.url||candidate.resolvedUrl);await addDownload(candidate.url||candidate.resolvedUrl,analysis);navigation.navigate('Downloads');}catch(e){setError(e.message);}finally{setBusy(false);}},[addDownload,navigation]);
 const candidates=result?.candidates||[];
 return <Screen keyboard><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.wrap}><Text style={s.title}>Links</Text><Text style={s.subtitle}>Inspect redirects, response type and ordinary public media candidates. VideoRip does not bypass authentication, paywalls or DRM.</Text><TextInput accessibilityLabel="Source URL" value={url} onChangeText={setUrl} autoCapitalize="none" autoCorrect={false} keyboardType="url" multiline placeholder="HTTP or HTTPS URL" style={s.input}/><Pressable accessibilityRole="button" accessibilityLabel="Analyse source" onPress={run} disabled={!url.trim()||busy} style={[s.primary,(!url.trim()||busy)&&s.disabled]}><Text style={s.primaryText}>Analyse source</Text></Pressable>{busy?<ActivityIndicator style={{marginTop:14}}/>:null}{error?<Text accessibilityLiveRegion="assertive" style={s.error}>{error}</Text>:null}
 {result?<View style={s.card}><Text style={s.heading}>{result.sourceType?.toUpperCase()} · {result.mediaType}</Text><Text style={s.meta}>{result.contentType||'Unknown MIME'}{result.size?` · ${formatBytes(result.size)}`:''}</Text><Text selectable style={s.url}>{result.resolvedUrl}</Text>{result.protected?<Text style={s.error}>Protected/authenticated source — no bypass attempted.</Text>:null}</View>:null}
 {result&&candidates.length===0?<View style={s.card}><Text style={s.meta}>No ordinary media candidates were found. The page may use script-generated, authenticated, protected or unsupported media.</Text></View>:null}
 {candidates.map((c,i)=><View key={`${c.url}-${i}`} style={s.card}><Text style={s.heading}>{c.sourceType?.toUpperCase()||'MEDIA'} · {c.mediaType||'unknown'}</Text><Text selectable numberOfLines={3} style={s.url}>{c.url}</Text><Pressable accessibilityRole="button" accessibilityLabel="Download this media candidate" onPress={()=>add(c)} style={s.primary}><Text style={s.primaryText}>Download this candidate</Text></Pressable></View>)}
 </ScrollView></Screen>;
}
const s=StyleSheet.create({wrap:{padding:18,paddingBottom:30},title:{fontSize:28,fontWeight:'900',color:'#0F172A'},subtitle:{color:'#475569',marginTop:6,lineHeight:21},input:{marginTop:16,minHeight:70,borderWidth:1,borderColor:'#94A3B8',borderRadius:12,padding:12,color:'#0F172A',textAlignVertical:'top',fontSize:16},primary:{minHeight:48,marginTop:12,borderRadius:12,backgroundColor:'#0B57D0',justifyContent:'center',alignItems:'center',paddingHorizontal:14},primaryText:{color:'#FFF',fontWeight:'900'},disabled:{opacity:.45},card:{backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0',borderRadius:16,padding:15,marginTop:14},heading:{fontSize:16,fontWeight:'900',color:'#0B57D0'},meta:{color:'#64748B',marginTop:6,lineHeight:20},url:{fontSize:12,color:'#334155',marginTop:8,lineHeight:18},error:{color:'#991B1B',marginTop:12,lineHeight:20}});
